// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Joxy",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Joxy",
            targets: ["App"],
            bundleIdentifier: "VincenzoPascarella.Joxy",
            teamIdentifier: "G9H564688N",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            additionalInfoPlistContentFilePath: "App/ExtraInfo.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "App",
            path: "App",
            exclude: ["./ExtraInfo.plist"],
            resources: [
                .process("Resources")
            ]
        )
    ]
)
